### ISSUE TITLE
[wishlist] mro.pm.meter: reset 

### ISSUE THREAD

**Issue by gurneyalex** [codup/odoo-eam#10]
I would like to define a meter such a 'time since maintenance' and have this to schedule maintenance every year for some equipment and every 6 month for other equipment, so ideally I'd like this meter to be reset to 0 after each scheduled maintenance. Currently, the only way I found is to have a reading type set to 'cng' and to input a negative delta equal to the current total value after the maintenance, but this is not quite satisfactory, and having a reset to 0 button would be nice. 

Or am I missing something ?

**Comment by wowas18** [comment]
If you need reset meter or set to predefined value then you must detach meter. Then attach it back.
