### ISSUE TITLE
mro.order: date_planned vs. date_scheduled clarification

### ISSUE THREAD

**Issue by gurneyalex** [codup/odoo-eam#12]
could you add a help for the two fields `date_planned` and `date_scheduled` the names have very close semantics for me and I totally don't understand what they are used for.

**Comment by gurneyalex** [comment]
https://github.com/codup/odoo-eam/blob/master/mro/mro.py#L262 does not help to understand, nor the various on change methods

**Comment by wowas18** [comment]
http://codup.com/en/component/content/article/93-applications/maintenance/192-mro-pm.html#comment-79
