### ISSUE TITLE
mro_pm: find_step logic

### ISSUE THREAD

**Issue by gurneyalex** [codup/odoo-eam#13]
I'm confused about the `find_step` implementation in mro.order (from mrp_pm). 

The return value is clearly in the interval[tmin, tmax] but I don't understand the underlying logic, especially the function is not monotonous as the [start, end] interval increases.

Could you consider adding a docstring explaining the logic?

**Comment by wowas18** [comment]
It for find optimal step within defined interval accuracy.

`Could you consider adding a docstring explaining the logic?`
No. Comments in code is bad practic.

**Comment by yvaucher** [comment]
@wowas18 you have a syntax error in your last sentence, the dot is misplaced.

You certainly meant:
`No comments in code is bad practice.`

**Comment by mdietrichc2c** [comment]
@wowas18 : I think I understand the method, but I'm not sure of which cases are not covered by this:
```
interval = end - start
if tmax < interval:
    return tmax
elif tmin > interval:
    return tmin
else:
    return interval
```

Can you provide me with an example?

**Comment by mdietrichc2c** [comment]
@wowas18 okay, after re-reading the code, I think I understand now the goal of the method: it is to divide the interval (end - start) in a number of steps (M, an integer) with the same value in the range [Tmin, Tmax]. The whole part using `M = M + 1`and `M = M - 1` is if adjustment after rounding M.

I can indeed see that using (start, end) of (1, 12), and (tmin, tmax) of (1, 2), I get M = 7 and a step of 11/7, while my code will return 2.
The fact is, it's not exactly evident (especially with your naming conventions) ; a single comment " `divide the interval (start, end) in equal steps, with a range between Tmin and Tmax` " would avoid issues.

**Comment by gurneyalex** [comment]
"find optimal step within defined interval accuracy" ok that's a good start. However the arguments to the method don't have informative names (tmin / tmax : do these relate to the accuracy), and what you are trying to optimize escapes me.  I plotted find_step(0, x, 0, 100) to try to see what the function looks like and got this:

![find_step1](https://cloud.githubusercontent.com/assets/2032807/10335616/535860d0-6cf2-11e5-99ac-04d299d41670.png)

and now I'm baffled :astonished:

**Comment by wowas18** [comment]
I agree that naming conventions is very bad :(
But code was written a long ago and in a hurry.

Comments is bad things because you can change code but you have not time for change comment. Old comments remain and will be more confused.
