### ISSUE TITLE
[QUESTION] V8: Asset Warehouse: Accounting Lines

### ISSUE THREAD

**Issue by IljaSchumacher** [codup/odoo-eam#25]
Hi codup.

In v8 accounting moves for realtime stock evaluation are only generated for "non-interal" stock locations.
You introduce a new type "Asset Location".

What should happen accounting-wise if I consume parts(with realtime evaluation)  from an Internal Stock Location (in the process of MRO maintenance) to the Asset Location of the Asset I repair?

Basically we need to track expenses for the spareparts (from InternalStock) used for MRO maintenance of an Asset in the AssetAccount that is set in Accounting/Assets.

Will your module generate such accounting moves?
As per now I dont see them generated so I dont know if it is my faulty config or the module is not designed to do that.

Many thanks and спасибо for your great work.

**Comment by wowas18** [comment]
MRO generate inventory moves according to inventory rules and routing. MRO don't have any integration with Accounting.
