### ISSUE TITLE
Cannot complete the workflow

### ISSUE THREAD

**Issue by higorvaz** [codup/odoo-eam#28]
Create Maintenance Order
Added Planned Parts (the parts I have on the Inventory)
Save Maintenance Order
Confirm Maintenance

After that cannot continue the wf even if [Force Reservation]
Please let me know if exists some wiki...
Higor

**Comment by higorvaz** [comment]
Found the way how to put the demo data on a new test database, but it is impossible to make that routes on a production enrivonment.
Thanks a lot for any help.
Higor

**Comment by wowas18** [comment]
Routes from standard module Warehouse. Please read how it configured from odoo book.
