### ISSUE TITLE
V8 MRO

### ISSUE THREAD

**Issue by bunhin** [codup/odoo-eam#36]
Please link to account move and journal entry, IMHO it should be no 1 priority otherwise these good modules in this repo that aim to fill the existing gap in odoo, become less useful.

Also please consider: most part used in maintenance will be expenses type, some may adjusted to increase asset value (if the part is significantly big in value and upgrade the asset,  let the user check)  So please consider to reduce the inventory valuation versus increase the expenses.  With this automated journal entry the double entry can be avoided, avoid being forget to journal the expenses and the stock value, and the real time financial condition can be maintain.

Regards,
Bun Hin

**Comment by wowas18** [comment]
Can you write detailed requirements for your bussiness case?
For example: when user click **some** button then create account move with following **some** source and **some** destination account and etc.
This will help to speed up implementation.

**Comment by wowas18** [comment]
Closed due to lack of feedback
