### ISSUE TITLE
BUG: Cannot consume parts already in stock (procurement order always created)

### ISSUE THREAD

**Issue by diggy128** [codup/odoo-eam#40]
When creating an mro.order and set a part, you cannot consume a part that is in stock. 
action_confirm ALWAYS creates a procurement order without checking stock available.

How to reproduce:
1. Create a new mro.order and set a needed part that is already in stock.
2. Confirm the order (status changes to Waiting Parts - 'released')
3. Force Parts reservation only tries to move stock in procurement order.

Consuming available parts is essential in a business where several parts are in stock for hot swapping, or even consumables.

Are there any plans to attend to this issue or is development halted at this point?

**Comment by wowas18** [comment]
Procurement order must always be created. It mean that parts need order from other location (in your case from stock).
