### ISSUE TITLE
Configure product

### ISSUE THREAD

**Issue by flammiag** [codup/odoo-eam#46]
Hi, I installed MRO on odoo 10. 
I used Request and order without problem. 
I don't understand hoow add the product to Order Maintenance. 
If I add a product, this product is always in "waiting for availability". 
How do I configure the product ? 
It is just a part of product, but it is not enough.

**Comment by wowas18** [comment]
Please check that you have correct setup of your [route and procurement rule](http://codup.com/en/component/content/article/93-applications/maintenance/191-mro.html#comment-408).
