### ISSUE TITLE
Translation pt

### ISSUE THREAD

**Issue by falexandresilva** [codup/odoo-eam#50]
At the module mro in i18n at the archive pt.po there is a error: an initial "av" before the comment.

av# Translation of Odoo Server.
# This file contains the translation of the following modules:
# 	* mro
#
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 9.0\n"

**Comment by wowas18** [comment]
fix in https://github.com/codup/odoo-eam/commit/ea3b9e692a886320afcf3f4b2664efe8a1bdb917
